<?php

namespace V3\App\Services\Explore\LessonData;

class Category5Lessons
{
    public static function getLessons(): array
    {
        return [
            1 => [
                [
                    "id" => 1,
                    "course_id" => 1,
                    "course_name" => "Scratch Programming",
                    "title" => "Lesson 1",
                    "goal" => "",
                    "objectives" => "",
                    "description" => "Introduction To Scratch Programming",
                    "assignment_description" => "",
                    "assignment_url" => "",
                    "material_url" => "https://linkschoolonline.com/assets/materials/scratch-lesson-1.pdf",
                    "video_url" => "https://youtu.be/m-Y3YqVo3rY",
                    "reading_url" => "https://sip.scratch.mit.edu/wp-content/uploads/2020/06/Getting-Started-With-Scratch-3.0.pdf",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/86802348358?pwd=jI2xH3RArMOw5h8JaM7WpBy0Y67aVK.1",
                    "recorded_url" => "https://drive.google.com/file/d/1SrsXz5GtRAyFcGjVrvTFAo7BMWhho-Iw/preview",
                    "date" => "2025-04-12 10:00"
                ],
                [
                    "id" => 2,
                    "course_id" => 1,
                    "course_name" => "Scratch Programming",
                    "title" => "Lesson 2",
                    "goal" => "",
                    "objectives" => "",
                    "description" => "Events & Animations",
                    "assignment_description" => "",
                    "assignment_url" => "",
                    "material_url" => "https://linkschoolonline.com/assets/materials/scratch-lesson-2.pdf",
                    "video_url" => "https://youtu.be/a9jx7Ziwt_k?si=8hCWhzCJ1_znYfuT",
                    "reading_url" => "https://sip.scratch.mit.edu/wp-content/uploads/2020/06/Getting-Started-With-Scratch-3.0.pdf",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/86802348358?pwd=jI2xH3RArMOw5h8JaM7WpBy0Y67aVK.1",
                    "recorded_url" => "https://drive.google.com/file/d/1smwnQs6v40UYgSMshS2x_BPzmJ2tBMst/preview",
                    "date" => "2025-04-14 10:00"
                ],
                [
                    "id" => 3,
                    "course_id" => 1,
                    "course_name" => "Scratch Programming",
                    "title" => "Lesson 3",
                    "goal" => "",
                    "objectives" => "",
                    "description" => "Learning Loops in Scratch",
                    "assignment_description" => "",
                    "assignment_url" => "https://linkschoolonline.com/assets/materials/scratch-assignment-3.pdf",
                    "material_url" => "https://linkschoolonline.com/assets/materials/scratch-lesson-3.pdf",
                    "video_url" => "https://youtu.be/FS_b6sHnuHo?si=zHKwpwegBwEMvS2I",
                    "reading_url" => "https://sip.scratch.mit.edu/wp-content/uploads/2020/06/Getting-Started-With-Scratch-3.0.pdf",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/86802348358?pwd=jI2xH3RArMOw5h8JaM7WpBy0Y67aVK.1",
                    "recorded_url" => "",
                    "date" => "2025-04-15 10:00"
                ],
                [
                    "id" => 4,
                    "course_id" => 1,
                    "course_name" => "Scratch Programming",
                    "title" => "Lesson 4",
                    "goal" => "",
                    "objectives" => "",
                    "description" => "User Inputs & Sensing",
                    "assignment_description" => "",
                    "assignment_url" => "https://linkschoolonline.com/assets/materials/scratch-assignment-4.pdf",
                    "material_url" => "https://linkschoolonline.com/assets/materials/scratch-lesson-4.pdf",
                    "video_url" => "https://youtu.be/ZynJhRAnzE8?si=PtxNfgU9F0MSjF4J",
                    "reading_url" => "https://sip.scratch.mit.edu/wp-content/uploads/2020/06/Getting-Started-With-Scratch-3.0.pdf",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/86802348358?pwd=jI2xH3RArMOw5h8JaM7WpBy0Y67aVK.1",
                    "recorded_url" => "https://drive.google.com/file/d/1yGTXVLuMUCGJu8L662jYa4QPS18ptTJG/preview",
                    "date" => "2025-04-16 10:00"
                ],
                [
                    "id" => 5,
                    "course_id" => 1,
                    "course_name" => "Scratch Programming",
                    "title" => "Lesson 5",
                    "goal" => "",
                    "objectives" => "",
                    "description" => "Variables & Simple Math",
                    "assignment_description" => "",
                    "assignment_url" => "https://linkschoolonline.com/assets/materials/scratch-assignment-5.pdf",
                    "material_url" => "https://linkschoolonline.com/assets/materials/scratch-lesson-5.pdf",
                    "video_url" => "https://youtu.be/nJ8scAn5k2I?si=p39uVj-C6ZREW6Df",
                    "reading_url" => "https://sip.scratch.mit.edu/wp-content/uploads/2020/06/Getting-Started-With-Scratch-3.0.pdf",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/86802348358?pwd=jI2xH3RArMOw5h8JaM7WpBy0Y67aVK.1",
                    "recorded_url" => "https://drive.google.com/file/d/1RulE55aD3Jmc7AAD-YUfQ8kpMQy9ddrV/preview",
                    "date" => "2025-04-17 10:00"
                ],
                [
                    "id" => 6,
                    "course_id" => 1,
                    "course_name" => "Scratch Programming",
                    "title" => "Lesson 6",
                    "goal" => "Learn conditional and simple AI in scratch",
                    "objectives" => "Kids will learn how to create game logic using events and conditionals",
                    "description" => "Conditional and Simple AI",
                    "assignment_description" => "",
                    "assignment_url" => "https://linkschoolonline.com/assets/materials/scratch-assignment-6.pdf",
                    "material_url" => "https://linkschoolonline.com/assets/materials/scratch-lesson-6.pdf",
                    "video_url" => "https://youtu.be/nJ8scAn5k2I?si=p39uVj-C6ZREW6Df",
                    "reading_url" => "https://sip.scratch.mit.edu/wp-content/uploads/2020/06/Getting-Started-With-Scratch-3.0.pdf",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/86802348358?pwd=jI2xH3RArMOw5h8JaM7WpBy0Y67aVK.1",
                    "recorded_url" => "https://drive.google.com/file/d/1RulE55aD3Jmc7AAD-YUfQ8kpMQy9ddrV/preview",
                    "date" => "2025-04-17 10:00"
                ],
                [
                    "id" => 7,
                    "course_id" => 1,
                    "course_name" => "Scratch Programming",
                    "title" => "Lesson 7",
                    "goal" => "Understand cloning in Scratch and how to use cloning blocks",
                    "objectives" => "Kids will learn how to create games with clones and earn points",
                    "description" => "Cloning and multiple sprites",
                    "assignment_description" => "",
                    "assignment_url" => "https://linkschoolonline.com/assets/materials/scratch-assignment-7.pdf",
                    "material_url" => "https://linkschoolonline.com/assets/materials/scratch-lesson-7.pdf",
                    "video_url" => "https://youtu.be/jKk7T4vlNLk?si=l4Zo4Kuy3uXawgLz",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/86802348358?pwd=jI2xH3RArMOw5h8JaM7WpBy0Y67aVK.1",
                    "recorded_url" => "https://drive.google.com/file/d/1NhfhDVLhavUEvCqqCusCJ744WnM9gz5D/preview",
                    "date" => "2025-04-19 10:00"
                ],
                [
                    "id" => 8,
                    "course_id" => 1,
                    "course_name" => "Scratch Programming",
                    "title" => "Lesson 8",
                    "goal" => "Understand how to develop simple games",
                    "objectives" => "Kids will learn how to create a catching game in Scratch",
                    "description" => "Creating a Simple Game in Scratch",
                    "assignment_description" => "",
                    "assignment_url" => "https://linkschoolonline.com/assets/materials/scratch-assignment-8.pdf",
                    "material_url" => "https://linkschoolonline.com/assets/materials/scratch-lesson-8.pdf",
                    "video_url" => "https://youtu.be/0VOO2JW6iEM?si=85YXB_ZZEH5WEZgr",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/86802348358?pwd=jI2xH3RArMOw5h8JaM7WpBy0Y67aVK.1",
                    "recorded_url" => "https://drive.google.com/file/d/1a0DOm4vRpJDv2AR0kXV3HkyGD4s9QaYI/preview",
                    "date" => "2025-04-21 10:00"
                ],
                [
                    "id" => 9,
                    "course_id" => 1,
                    "course_name" => "Scratch Programming",
                    "title" => "Lesson 9",
                    "goal" => "Simulating gravity in Scratch",
                    "objectives" => "Kids will learn how to create a scrolling backdrop and gravity game",
                    "description" => "Scrolling Backdrop and Gravity in Scratch",
                    "assignment_description" => "",
                    "assignment_url" => "https://linkschoolonline.com/assets/materials/scratch-assignment-9.pdf",
                    "material_url" => "https://linkschoolonline.com/assets/materials/scratch-lesson-9.pdf",
                    "video_url" => "https://youtu.be/dofs21zXPV8?si=S9vl_GhuWX67N8Ra",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/86802348358?pwd=jI2xH3RArMOw5h8JaM7WpBy0Y67aVK.1",
                    "recorded_url" => "https://drive.google.com/file/d/10upEvPPNLCDwdr1RjT5TLobUtn5GpOmZ/preview",
                    "date" => "2025-04-22 10:00"
                ],
                [
                    "id" => 10,
                    "course_id" => 1,
                    "course_name" => "Scratch Programming",
                    "title" => "Lesson 10",
                    "goal" => "Learn how to animate stories",
                    "objectives" => "Kids will learn how to animate stories in Scratch and create a birthday card",
                    "description" => "Story & Animation",
                    "assignment_description" => "",
                    "assignment_url" => "https://linkschoolonline.com/assets/materials/scratch-assignment-10.pdf",
                    "material_url" => "",
                    "video_url" => "https://youtu.be/PfNGtooA5E4?si=WJ0076Tn3jyGerAC",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/86802348358?pwd=jI2xH3RArMOw5h8JaM7WpBy0Y67aVK.1",
                    "recorded_url" => "https://drive.google.com/file/d/1R2BN8By5VuCJfznGdvx47AO2MxDwJC7d/preview",
                    "date" => "2025-04-23 10:00"
                ],
                [
                    "id" => 11,
                    "course_id" => 1,
                    "course_name" => "Scratch Programming",
                    "title" => "Lesson 11",
                    "goal" => "Learn how to create a pong game",
                    "objectives" => "Kids will learn how to add levels while creating games",
                    "description" => "Advanced Scratch Game",
                    "assignment_description" => "",
                    "assignment_url" => "https://linkschoolonline.com/assets/materials/scratch-assignment-11.pdf",
                    "material_url" => "https://linkschoolonline.com/assets/materials/scratch-lesson-11.pdf",
                    "video_url" => "https://youtu.be/bIjCOHLbdLQ?si=CVWb6jomCKE5NFhy",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/86802348358?pwd=jI2xH3RArMOw5h8JaM7WpBy0Y67aVK.1",
                    "recorded_url" => "https://drive.google.com/file/d/155vrPnTvvo8EOYjt0S3DARqvo5W3Heff/preview",
                    "date" => "2025-04-24 10:00"
                ],
                [
                    "id" => 12,
                    "course_id" => 1,
                    "course_name" => "Scratch Programming",
                    "title" => "Lesson 12",
                    "goal" => "Understand sounds in games",
                    "objectives" => "Kids will learn how to add background music to games",
                    "description" => "Using Background Music to Make Games",
                    "assignment_description" => "",
                    "assignment_url" => "",
                    "material_url" => "https://linkschoolonline.com/assets/materials/scratch-lesson-12.pdf",
                    "video_url" => "https://youtu.be/2OvriEo2XV0?si=7fsRCaTh7eu4x__e",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/86802348358?pwd=jI2xH3RArMOw5h8JaM7WpBy0Y67aVK.1",
                    "recorded_url" => "",
                    "date" => "2025-04-25 10:00"
                ],
                [
                    "id" => 13,
                    "course_id" => 1,
                    "course_name" => "Scratch Programming",
                    "title" => "Congratulations",
                    "goal" => "Congratulations on your Participation in the Scratch Programming Course!",
                    "objectives" => "",
                    "description" => "Final Day & Certificate!",
                    "assignment_description" => "",
                    "assignment_url" => "",
                    "material_url" => "",
                    "video_url" => "https://youtu.be/MKUZ7pwuWnI?si=Jskq8cAl59zTiOX9",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "",
                    "recorded_url" => "",
                    "date" => "2025-04-26 10:00"
                ]
            ],

            2 => [
                [
                    "id" => 1,
                    "course_id" => 2,
                    "course_name" => "Graphics Design",
                    "title" => "Lesson 1",
                    "goal" => "Understand how graphic design is used in the real world.",
                    "objectives" => "Help kids understand what graphic design is all about",
                    "description" => "Introduction to Graphic Design",
                    "assignment_description" => "",
                    "assignment_url" => "https://linkschoolonline.com/assets/materials/graphic-assignment-1.pdf",
                    "material_url" => "https://linkschoolonline.com/assets/materials/graphic-lesson-1.pdf",
                    "lesson_id" => 2,
                    "video_url" => "https://youtu.be/RYjPLK2uGoo",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/83508995321?pwd=78fYlgBGG0i2HFEtaSfFzqbyudQ0Ax.1",
                    "recorded_url" => "https://drive.google.com/file/d/1REVGQKqIiwhIOdVqZz4kFAVzZp4_hPvg/preview",
                    "date" => "2025-07-26 12:00"
                ],
                [
                    "id" => 2,
                    "course_id" => 2,
                    "course_name" => "Graphics Design",
                    "title" => "Lesson 2",
                    "goal" => "To be able to navigate between the Canva Homepage and the Design Editor.",
                    "objectives" => "To help kids use tools effectively to create and edit designs",
                    "description" => "Getting Started with Canva",
                    "assignment_description" => "",
                    "assignment_url" => "https://linkschoolonline.com/assets/materials/graphic-assignment-2.pdf",
                    "material_url" => "https://linkschoolonline.com/assets/materials/graphic-lesson-2.pdf",
                    "lesson_id" => 2,
                    "video_url" => "https://youtu.be/QBe2O3zP3P8?si=wY_cuSDoe3KA_V95",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/83508995321?pwd=78fYlgBGG0i2HFEtaSfFzqbyudQ0Ax.1",
                    "recorded_url" => "https://drive.google.com/file/d/1OcF39DWuSSRvVHH_Mo7nE6TXjvEJF2lJ/preview",
                    "date" => "2025-04-14 10:00"
                ],
                [
                    "id" => 3,
                    "course_id" => 2,
                    "course_name" => "Graphics Design",
                    "title" => "Lesson 3",
                    "goal" => "Understand how colors and fonts influence design.",
                    "objectives" => "Help kids learn how to apply color and typography principles in a fun and interactive design activity.",
                    "description" => "Understanding Color Theory & Typography",
                    "assignment_description" => "",
                    "assignment_url" => "https://linkschoolonline.com/assets/materials/graphic-assignment-3.pdf",
                    "material_url" => "https://linkschoolonline.com/assets/materials/graphic-lesson-3.pdf",
                    "lesson_id" => 3,
                    "video_url" => "https://youtu.be/PBJraThAbnM?si=5H4rusBexyt2_wxK",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/83508995321?pwd=78fYlgBGG0i2HFEtaSfFzqbyudQ0Ax.1",
                    "recorded_url" => "https://drive.google.com/file/d/1JUO9JO-IwGpPlbuRu7H7J7CdxQMbIcZt/preview",
                    "date" => "2025-04-15 10:00"
                ],
                [
                    "id" => 4,
                    "course_id" => 2,
                    "course_name" => "Graphics Design",
                    "title" => "Lesson 4",
                    "goal" => "To explore how shapes are used in logos",
                    "objectives" => "To help kids understand the power of shapes in design",
                    "description" => "Working with Shapes & Logos",
                    "assignment_description" => "",
                    "assignment_url" => "https://linkschoolonline.com/assets/materials/graphic-assignment-4.pdf",
                    "material_url" => "https://linkschoolonline.com/assets/materials/graphic-lesson-4.pdf",
                    "lesson_id" => 4,
                    "video_url" => "https://youtu.be/JAqQ1zOF0gk?si=LUbUtGlq_vT98EBM",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/83508995321?pwd=78fYlgBGG0i2HFEtaSfFzqbyudQ0Ax.1",
                    "recorded_url" => "https://drive.google.com/file/d/1vC5d_zcC6H8jjERWuOvu04XzJkecQ48E/preview",
                    "date" => "2025-04-16 10:00"
                ],
                [
                    "id" => 5,
                    "course_id" => 2,
                    "course_name" => "Graphics Design",
                    "title" => "Lesson 5",
                    "goal" => "Learn how to balance text and visuals",
                    "objectives" => "Understand what makes a poster or flyer effective",
                    "description" => "Designing Posters & Flyers",
                    "assignment_description" => "",
                    "assignment_url" => "https://linkschoolonline.com/assets/materials/graphic-assignment-5.pdf",
                    "material_url" => "https://linkschoolonline.com/assets/materials/graphic-lesson-5.pdf",
                    "video_url" => "https://youtu.be/Md0q-cJ9eRc?si=IJjqGp0XVhsAToWF",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/83508995321?pwd=78fYlgBGG0i2HFEtaSfFzqbyudQ0Ax.1",
                    "recorded_url" => "",
                    "date" => "2025-04-17 10:00"
                ],
                [
                    "id" => 6,
                    "course_id" => 2,
                    "course_name" => "Graphics Design",
                    "title" => "Lesson 6",
                    "goal" => "Practice creating engaging billboards",
                    "objectives" => "Learn the principles of effective billboard and website design",
                    "description" => "Billboards and Web Banners",
                    "assignment_description" => "",
                    "assignment_url" => "https://linkschoolonline.com/assets/materials/graphic-assignment-6.pdf",
                    "material_url" => "https://linkschoolonline.com/assets/materials/graphic-lesson-6.pdf",
                    "video_url" => "https://youtu.be/yJ-nJsl3kEk?si=By6NLOpluNXlMev-",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/83508995321?pwd=78fYlgBGG0i2HFEtaSfFzqbyudQ0Ax.1",
                    "recorded_url" => "https://drive.google.com/file/d/1w0NFJY1gkjlIOqAM1p4ueKAVknpt2lQ_/preview",
                    "date" => "2025-04-18 10:00"
                ],
                [
                    "id" => 7,
                    "course_id" => 2,
                    "course_name" => "Graphics Design",
                    "title" => "Lesson 7",
                    "goal" => "Understand how to size graphics properly for different social media platforms",
                    "objectives" => "Create an Instagram post featuring Kids Fashion sales using graphic design tools",
                    "description" => "Creating Social Media Graphics",
                    "assignment_description" => "",
                    "assignment_url" => "https://linkschoolonline.com/assets/materials/graphic-assignment-7.pdf",
                    "material_url" => "https://linkschoolonline.com/assets/materials/graphic-lesson-7.pdf",
                    "video_url" => "https://youtu.be/P3Ox9eq0JeY?si=GzvPrcHx1wR2Zm7z",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/83508995321?pwd=78fYlgBGG0i2HFEtaSfFzqbyudQ0Ax.1",
                    "recorded_url" => "https://drive.google.com/file/d/1aAhZoZRPkesqtQNSAVTmar3rMSPqmFhC/preview",
                    "date" => "2025-04-19 10:00"
                ],
                [
                    "id" => 8,
                    "course_id" => 2,
                    "course_name" => "Graphics Design",
                    "title" => "Lesson 8",
                    "goal" => "Understand the basics of photo editing, including cropping, resizing, and filters",
                    "objectives" => "Enhance an image by adjusting brightness and contrast",
                    "description" => "Simple Photo Editing Basics in Canva",
                    "assignment_description" => "",
                    "assignment_url" => "https://linkschoolonline.com/assets/materials/graphic-assignment-8.pdf",
                    "material_url" => "https://linkschoolonline.com/assets/materials/graphic-lesson-8.pdf",
                    "video_url" => "https://youtu.be/9NAUMb3RV64?si=2_2EywR2Irhk2M02",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/83508995321?pwd=78fYlgBGG0i2HFEtaSfFzqbyudQ0Ax.1",
                    "recorded_url" => "https://drive.google.com/file/d/1tp4uxSb4Ak5X5boLpN1aGMWWXXkkZnTw/preview",
                    "date" => "2025-04-21 10:00"
                ],
                [
                    "id" => 9,
                    "course_id" => 2,
                    "course_name" => "Graphics Design",
                    "title" => "Lesson 9",
                    "goal" => "Understand animation features in Canva",
                    "objectives" => "Create engaging animations and GIFs",
                    "description" => "Let us Make it Move! Learning Animation & GIFs",
                    "assignment_description" => "",
                    "assignment_url" => "https://linkschoolonline.com/assets/materials/graphic-assignment-9.pdf",
                    "material_url" => "https://linkschoolonline.com/assets/materials/graphic-lesson-9.pdf",
                    "video_url" => "https://youtu.be/mgmg83A74ik?si=Iqxk5HXw6GxeWUZB",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/83508995321?pwd=78fYlgBGG0i2HFEtaSfFzqbyudQ0Ax.1",
                    "recorded_url" => "https://drive.google.com/file/d/1tKzAYve3Dz7u6M1WNby81S3Q1C_dv6qg/preview",
                    "date" => "2025-04-22 10:00"
                ],
                [
                    "id" => 10,
                    "course_id" => 2,
                    "course_name" => "Graphics Design",
                    "title" => "Lesson 10",
                    "goal" => "Apply color, font, layout, and creativity by designing a storybook cover",
                    "objectives" => "Combine fonts, colors, and shapes to match a story's theme",
                    "description" => "Designing a Storybook Cover",
                    "assignment_description" => "",
                    "assignment_url" => "https://linkschoolonline.com/assets/materials/graphic-assignment-10.pdf",
                    "material_url" => "https://linkschoolonline.com/assets/materials/graphic-lesson-10.pdf",
                    "video_url" => "https://youtu.be/lA38yAnXAUI?si=_72B3uQyOeKeplpT",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/83508995321?pwd=78fYlgBGG0i2HFEtaSfFzqbyudQ0Ax.1",
                    "recorded_url" => "https://drive.google.com/file/d/1HnVR7XT2nbYD55_wV_Xclcv200EITWLQ/preview",
                    "date" => "2025-04-23 10:00"
                ],
                [
                    "id" => 11,
                    "course_id" => 2,
                    "course_name" => "Graphics Design",
                    "title" => "Lesson 11",
                    "goal" => "Introduce how businesses use design to look professional",
                    "objectives" => "Create a letterhead and business card using Canva",
                    "description" => "Letterhead & Business Card Design",
                    "assignment_description" => "",
                    "assignment_url" => "https://linkschoolonline.com/assets/materials/graphic-assignment-11.pdf",
                    "material_url" => "https://linkschoolonline.com/assets/materials/graphic-lesson-11.pdf",
                    "video_url" => "https://youtu.be/yFLr1SLsZGs?si=dS2iP2DlQ3G7977H",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/83508995321?pwd=78fYlgBGG0i2HFEtaSfFzqbyudQ0Ax.1",
                    "recorded_url" => "https://drive.google.com/file/d/1LvPexXxKZq35n1d74nE-GYpnPbXrJXCM/preview",
                    "date" => "2025-04-24 10:00"
                ],
                [
                    "id" => 12,
                    "course_id" => 2,
                    "course_name" => "Graphics Design",
                    "title" => "Lesson 12",
                    "goal" => "",
                    "objectives" => "",
                    "description" => "Portfolio Development and Exploring AI for Image Generation",
                    "assignment_description" => "",
                    "assignment_url" => "",
                    "material_url" => "https://linkschoolonline.com/assets/materials/graphic-lesson-12.pdf",
                    "video_url" => "https://youtu.be/lA38yAnXAUI?si=_72B3uQyOeKeplpT",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/83508995321?pwd=78fYlgBGG0i2HFEtaSfFzqbyudQ0Ax.1",
                    "recorded_url" => "",
                    "date" => "2025-04-25 10:00"
                ],
                [
                    "id" => 13,
                    "course_id" => 2,
                    "course_name" => "Graphics Design",
                    "title" => "Congratulations",
                    "goal" => "Congratulations on your Participation in the Graphics Design Course!",
                    "objectives" => "",
                    "description" => "Final Day & Certificate!",
                    "assignment_description" => "",
                    "assignment_url" => "",
                    "material_url" => "",
                    "video_url" => "https://youtu.be/sQdP0fNLPKI?si=5GdzH3s-gjrX236s",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "",
                    "recorded_url" => "",
                    "date" => "2025-04-26 10:00"
                ]
            ],
            3 => [
                [
                    "id" => 1,
                    "course_id" => 3,
                    "course_name" => "Web Development",
                    "title" => "Lesson 1",
                    "goal" => "Help kids understand what a website is, why it's important, and how it works.",
                    "objectives" => "Teach kids the basics of web design, including HTML, CSS, and website building tools, to create their own functional websites.",
                    "description" => "Introduction to Websites",
                    "assignment_description" => "",
                    "assignment_url" => "https://linkschoolonline.com/assets/materials/web-assignment-1.pdf",
                    "material_url" => "https://linkschoolonline.com/assets/materials/web-development-lesson-1.pdf",
                    "video_url" => "https://youtu.be/kMyvWPLMEJM",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/89998434112?pwd=DOSDhKb2FUqb2LVNG7KazqPOGqml2C.1",
                    "recorded_url" => "https://drive.google.com/file/d/1VCWagxQXD8rhOO0XOKHkGDwq1ct2Gdv8/preview",
                    "date" => "2025-05-17 12:00"
                ],
                [
                    "id" => 2,
                    "course_id" => 3,
                    "course_name" => "Web Development",
                    "title" => "Lesson 2",
                    "goal" => "Help kids understand what a website is, why it's important, and how it works.",
                    "objectives" => "Teach kids the basics of web design, including HTML, CSS, and website building tools, to create their own functional websites.",
                    "description" => "Creating and Publishing your first Website on Google Sites",
                    "assignment_description" => "",
                    "assignment_url" => "https://linkschoolonline.com/assets/materials/web-assignment-2.pdf",
                    "material_url" => "https://linkschoolonline.com/assets/materials/web-development-lesson-2.pdf",
                    "video_url" => "https://youtu.be/c5oGdCXN3-o",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/89998434112?pwd=DOSDhKb2FUqb2LVNG7KazqPOGqml2C.1",
                    "recorded_url" => "https://drive.google.com/file/d/1hKmb0d7KnAyF1vMLUggfO43s9gDhXayI/preview",
                    "date" => "2025-04-14 10:00"
                ],
                [
                    "id" => 3,
                    "course_id" => 3,
                    "course_name" => "Web Development",
                    "title" => "Lesson 3",
                    "goal" => "Help kids understand what a website is, why it's important, and how it works.",
                    "objectives" => "Understand the purpose of HTML.",
                    "description" => "Understanding HTML Tags",
                    "assignment_description" => "",
                    "assignment_url" => "",
                    "material_url" => "https://linkschoolonline.com/assets/materials/web-development-lesson-3.pdf",
                    "video_url" => "https://youtu.be/UdXFwuIJkOA?si=-A2yKncfwCjstIxi",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/89998434112?pwd=DOSDhKb2FUqb2LVNG7KazqPOGqml2C.1",
                    "recorded_url" => "https://drive.google.com/file/d/1GR0PIPmFbci2lUovUSEdSgHBJL5j7e50/preview",
                    "date" => "2025-04-15 10:00"
                ],
                [
                    "id" => 4,
                    "course_id" => 3,
                    "course_name" => "Web Development",
                    "title" => "Lesson 4",
                    "goal" => "Help kids understand what a website is, why it's important, and how it works.",
                    "objectives" => "Introduce HTML tables and their attributes.",
                    "description" => "Understanding Table Tags and Attributes",
                    "assignment_description" => "",
                    "assignment_url" => "",
                    "material_url" => "https://linkschoolonline.com/assets/materials/web-development-lesson-4.pdf",
                    "video_url" => "https://youtu.be/0RrPNwWZDWA?si=wd_z1lP306HieQ5x",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/89998434112?pwd=DOSDhKb2FUqb2LVNG7KazqPOGqml2C.1",
                    "recorded_url" => "https://drive.google.com/file/d/1levhA07IZd2ud-yuZNVE9xGZjulWhkj5/preview",
                    "date" => "2025-04-16 10:00"
                ],
                [
                    "id" => 5,
                    "course_id" => 3,
                    "course_name" => "Web Development",
                    "title" => "Lesson 5",
                    "goal" => "Help kids understand what a website is, why it's important, and how it works.",
                    "objectives" => "Teach students how to apply inline CSS styles to HTML elements.",
                    "description" => "Introduction to Basic Inline Styling",
                    "assignment_description" => "",
                    "assignment_url" => "",
                    "material_url" => "https://linkschoolonline.com/assets/materials/web-development-lesson-5.pdf",
                    "video_url" => "https://youtu.be/3WYm4HLNxhk?si=in7Bl_bqBc_Ba3OM",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/89998434112?pwd=DOSDhKb2FUqb2LVNG7KazqPOGqml2C.1",
                    "recorded_url" => "https://drive.google.com/file/d/15a1arQwdHpnjUmXE3FPXMkL5oWqMuFAi/preview",
                    "date" => "2025-04-17 10:00"
                ],
                [
                    "id" => 6,
                    "course_id" => 3,
                    "course_name" => "Web Development",
                    "title" => "Lesson 6",
                    "goal" => "Help kids understand what a website is, why it's important, and how it works.",
                    "objectives" => "Teach students how to organize images using HTML tables.",
                    "description" => "Creating a Picture Gallery Using Tables and Rows",
                    "assignment_description" => "",
                    "assignment_url" => "",
                    "material_url" => "https://linkschoolonline.com/assets/materials/web-development-lesson-6.pdf",
                    "video_url" => "https://youtu.be/-o5VxVPMDBk?si=PvEO7kphZ-QsEVrD",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/89998434112?pwd=DOSDhKb2FUqb2LVNG7KazqPOGqml2C.1",
                    "recorded_url" => "",
                    "date" => "2025-04-18 10:00"
                ],
                [
                    "id" => 7,
                    "course_id" => 3,
                    "course_name" => "Web Development",
                    "title" => "Lesson 7",
                    "goal" => "Help kids understand what a website is, why it's important, and how it works.",
                    "objectives" => "Introduce students to CSS and its role in web design.",
                    "description" => "Introduction to CSS Basics",
                    "assignment_description" => "",
                    "assignment_url" => "",
                    "material_url" => "https://linkschoolonline.com/assets/materials/web-development-lesson-7.pdf",
                    "video_url" => "https://youtu.be/mApWmqzWifk?si=07QJ6JKF_g1tCvrg",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/89998434112?pwd=DOSDhKb2FUqb2LVNG7KazqPOGqml2C.1",
                    "recorded_url" => "https://drive.google.com/file/d/12bqSQt1ASGjMvllSTmB-tBuntF_YqyGi/preview",
                    "date" => "2025-04-19 10:00"
                ],
                [
                    "id" => 8,
                    "course_id" => 3,
                    "course_name" => "Web Development",
                    "title" => "Lesson 8",
                    "goal" => "Help kids understand what a website is, why it's important, and how it works.",
                    "objectives" => "Teach students how to create a simple navigation system for their web pages.",
                    "description" => "Navigation and Layout",
                    "assignment_description" => "",
                    "assignment_url" => "",
                    "material_url" => "https://linkschoolonline.com/assets/materials/web-development-lesson-8.pdf",
                    "video_url" => "https://youtu.be/f1ZIRvyefsc?si=tKJ8R9uTDt4U-7fX",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/89998434112?pwd=DOSDhKb2FUqb2LVNG7KazqPOGqml2C.1",
                    "recorded_url" => "https://drive.google.com/file/d/1hrEZoNCrNv1XONrXfJ1KfWeAbGCXupbj/preview",
                    "date" => "2025-04-21 10:00"
                ],
                [
                    "id" => 9,
                    "course_id" => 3,
                    "course_name" => "Web Development",
                    "title" => "Lesson 9",
                    "goal" => "Help kids understand what a website is, why it's important, and how it works.",
                    "objectives" => "Teach students how to collect user input using HTML forms.",
                    "description" => "Creating Forms in HTML",
                    "assignment_description" => "",
                    "assignment_url" => "",
                    "material_url" => "https://linkschoolonline.com/assets/materials/web-development-lesson-9.pdf",
                    "video_url" => "https://youtu.be/8myzaNT0zHc?si=VHrtmOL1kN4Y0vmq",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/89998434112?pwd=DOSDhKb2FUqb2LVNG7KazqPOGqml2C.1",
                    "recorded_url" => "https://drive.google.com/file/d/1B0C0WjR7kwqmGNe6O4Zb-sNElP0F9cY0/preview",
                    "date" => "2025-04-22 10:00"
                ],
                [
                    "id" => 10,
                    "course_id" => 3,
                    "course_name" => "Web Development",
                    "title" => "Lesson 10",
                    "goal" => "Help kids understand what a website is, why it's important, and how it works.",
                    "objectives" => "Teach students how to add videos to a webpage using HTML.",
                    "description" => "Adding Videos and Embedding YouTube Videos",
                    "assignment_description" => "",
                    "assignment_url" => "",
                    "material_url" => "https://linkschoolonline.com/assets/materials/web-development-lesson-10.pdf",
                    "video_url" => "https://youtu.be/fglEBHUg1zI?si=yHweg7sMMes0-vJx",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/89998434112?pwd=DOSDhKb2FUqb2LVNG7KazqPOGqml2C.1",
                    "recorded_url" => "https://drive.google.com/file/d/1KgLMZLpNG9DoPRUTmiqYCiU64jpMgrJi/preview",
                    "date" => "2025-04-23 10:00"
                ],
                [
                    "id" => 11,
                    "course_id" => 3,
                    "course_name" => "Web Development",
                    "title" => "Lesson 11",
                    "goal" => "Help kids understand what a website is, why it's important, and how it works.",
                    "objectives" => "Introduce students to the fundamentals of good web design.",
                    "description" => "Principles of Web Design",
                    "assignment_description" => "",
                    "assignment_url" => "",
                    "material_url" => "https://linkschoolonline.com/assets/materials/web-development-lesson-11.pdf",
                    "video_url" => "https://youtu.be/xOslMWNv0Ts?si=M03Hp_gaIyB-l7bz",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/89998434112?pwd=DOSDhKb2FUqb2LVNG7KazqPOGqml2C.1",
                    "recorded_url" => "https://drive.google.com/file/d/1U4UTOYwFFOH2XrTj2f1Frrl4hXzlE5vU/preview",
                    "date" => "2025-04-24 10:00"
                ],
                [
                    "id" => 12,
                    "course_id" => 3,
                    "course_name" => "Web Development",
                    "title" => "Lesson 12",
                    "goal" => "Help kids understand what a website is, why it's important, and how it works.",
                    "objectives" => "Teach students how to create a multi-page website using HTML and CSS.",
                    "description" => "Building a Family Website",
                    "assignment_description" => "",
                    "assignment_url" => "",
                    "material_url" => "https://linkschoolonline.com/assets/materials/web-development-lesson-12.pdf",
                    "video_url" => "https://youtu.be/Htsn3dw3iR0?si=0YU44J2DfzgtOYfX",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/89998434112?pwd=DOSDhKb2FUqb2LVNG7KazqPOGqml2C.1",
                    "recorded_url" => "https://youtu.be/Htsn3dw3iR0?si=0YU44J2DfzgtOYfX",
                    "date" => "2025-04-25 10:00"
                ],
                [
                    "id" => 13,
                    "course_id" => 3,
                    "course_name" => "Web Development",
                    "title" => "Congratulations",
                    "goal" => "Congratulations on your Participation in the Website Development Course!",
                    "objectives" => "",
                    "description" => "Final Day & Certificate!",
                    "assignment_description" => "",
                    "assignment_url" => "",
                    "material_url" => "",
                    "video_url" => "https://youtu.be/WwjpmB3JaD0?si=YB1um3gPnAxsmP8A",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "",
                    "recorded_url" => "",
                    "date" => "2025-04-26 10:00"
                ]
            ],
        ];
    }
}
