<?php

namespace V3\App\Services\Explore\LessonData;

class Category4Lessons
{
    public static function getLessons(): array
    {
        return [
            1 => [
                [
                    "id" => 1,
                    "course_id" => 1,
                    "course_name" => "Scratch Programming",
                    "title" => "Recap",
                    "goal" => "",
                    "objectives" => "",
                    "description" => "Scratch Basics",
                    "assignment_description" => "",
                    "assignment_url" => "",
                    "material_url" => "https://linkschoolonline.com/assets/materials/SCARTCH-BASICS-RECAP.pdf",
                    "video_url" => "https://youtu.be/seo4kxi2Rqc?si=Bc2mAXlxnLV4RTD0",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/86829896685?pwd=OxuWHkyEZ2TVXe5rwJlZ6cnLyqk4XF.1",
                    "recorded_url" => "https://drive.google.com/file/d/1Vg1t_QfNhseerfVAxJCzoTBvpk6ZVFHd/preview",
                    "date" => "2025-05-17 12:00"
                ],
                [
                    "id" => 2,
                    "course_id" => 1,
                    "course_name" => "Scratch Programming",
                    "title" => "Lesson 1",
                    "goal" => "",
                    "objectives" => "",
                    "description" => "Expressive Motion Animation",
                    "assignment_description" => "",
                    "assignment_url" => "",
                    "material_url" => "https://linkschoolonline.com/assets/materials/Expressive-motion-Animation.pdf",
                    "video_url" => "https://youtu.be/E7Iabqdny7U?si=vbey4i4D4PAg1Awc",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/86829896685?pwd=OxuWHkyEZ2TVXe5rwJlZ6cnLyqk4XF.1",
                    "recorded_url" => "https://drive.google.com/file/d/1Lr1Xve12lvih8XUdYwGSwpuzNgQitGrZ/preview",
                    "date" => "2025-05-24 12:00"
                ],
                [
                    "id" => 3,
                    "course_id" => 1,
                    "course_name" => "Scratch Programming",
                    "title" => "Lesson 2",
                    "goal" => "",
                    "objectives" => "",
                    "description" => "Animation Magic with Scratch",
                    "assignment_description" => "",
                    "assignment_url" => "https://linkschoolonline.com/assets/materials/animation-magic-project.pdf",
                    "material_url" => "https://linkschoolonline.com/assets/materials/ANIMATION-MAGIC-WITH-SCRATCH.pdf",
                    "video_url" => "https://youtu.be/Yr1WkEbQv30",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/86829896685?pwd=OxuWHkyEZ2TVXe5rwJlZ6cnLyqk4XF.1",
                    "recorded_url" => "https://drive.google.com/file/d/1h_6XBZX5hfHtny3yjwfERBQn69aUKCWn/preview",
                    "date" => "2025-05-31 12:00"
                ],
                [
                    "id" => 4,
                    "course_id" => 1,
                    "course_name" => "Scratch Programming",
                    "title" => "Lesson 3",
                    "goal" => "",
                    "objectives" => "",
                    "description" => "Amazing Animation with Code",
                    "assignment_description" => "",
                    "assignment_url" => "",
                    "material_url" => "https://linkschoolonline.com/assets/materials/Amazing-animation-with-code.pdf",
                    "video_url" => "https://youtu.be/teAw4Vp7p40",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/86829896685?pwd=OxuWHkyEZ2TVXe5rwJlZ6cnLyqk4XF.1",
                    "recorded_url" => "https://drive.google.com/file/d/1oLDsnHzvA2u6fQrNodtu8EAnXxU1SavX/preview",
                    "date" => "2025-06-07 12:00"
                ],
                [
                    "id" => 5,
                    "course_id" => 1,
                    "course_name" => "Scratch Programming",
                    "title" => "Lesson 4",
                    "goal" => "",
                    "objectives" => "",
                    "description" => "Scratch Art with Backdrop",
                    "assignment_description" => "",
                    "assignment_url" => "",
                    "material_url" => "https://linkschoolonline.com/assets/materials/SCATCH-ART-WITH-BACKDROP.pdf",
                    "video_url" => "https://youtu.be/f27N2JOUzgo",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/86829896685?pwd=OxuWHkyEZ2TVXe5rwJlZ6cnLyqk4XF.1",
                    "recorded_url" => "https://drive.google.com/file/d/1oLDsnHzvA2u6fQrNodtu8EAnXxU1SavX/preview",
                    "date" => "2025-06-14 12:00"
                ],
                [
                    "id" => 6,
                    "course_id" => 1,
                    "course_name" => "Scratch Programming",
                    "title" => "Lesson 5",
                    "goal" => "",
                    "objectives" => "",
                    "description" => "AI Lesson: Bringing Animation to Life with AI Voice",
                    "assignment_description" => "",
                    "assignment_url" => "",
                    "material_url" => "https://linkschoolonline.com/assets/materials/BRINGING-ANIMATION-TO-LIFE.pdf",
                    "video_url" => "https://youtu.be/CtMeehHtDuU",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/86829896685?pwd=OxuWHkyEZ2TVXe5rwJlZ6cnLyqk4XF.1",
                    "recorded_url" => "https://drive.google.com/file/d/12KL8B68JcDlPszJ4Yv9EAKFUAM8uuIlB/preview",
                    "date" => "2025-06-21 12:00"
                ],
                [
                    "id" => 7,
                    "course_id" => 1,
                    "course_name" => "Scratch Programming",
                    "title" => "Lesson 6",
                    "goal" => "",
                    "objectives" => "",
                    "description" => "Uploading Sprite and Backdrop",
                    "assignment_description" => "",
                    "assignment_url" => "",
                    "material_url" => "https://linkschoolonline.com/assets/materials/uploading-sprite-and-backdrop.pdf",
                    "video_url" => "https://youtu.be/o8P1zvm_Bms",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/86829896685?pwd=OxuWHkyEZ2TVXe5rwJlZ6cnLyqk4XF.1",
                    "recorded_url" => "https://drive.google.com/file/d/1Tt0XkaD-4buU7HJacl2PzxZKlXWJCtf-/preview",
                    "date" => "2025-06-28 12:00"
                ],
                [
                    "id" => 8,
                    "course_id" => 1,
                    "course_name" => "Scratch Programming",
                    "title" => "Lesson 7",
                    "goal" => "",
                    "objectives" => "",
                    "description" => "Building Animated stories to Life using AI Voice",
                    "assignment_description" => "",
                    "assignment_url" => "",
                    "material_url" => "https://linkschoolonline.com/assets/materials/BRINGING-ANIMATED-STORIES-TO-LIFE-USING-AI-VOICE.pdf",
                    "video_url" => "https://youtu.be/-DaehTcw9ug",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/86829896685?pwd=OxuWHkyEZ2TVXe5rwJlZ6cnLyqk4XF.1",
                    "recorded_url" => "",
                    "date" => "2025-07-05 12:00"
                ],
                [
                    "id" => 9,
                    "course_id" => 1,
                    "course_name" => "Scratch Programming",
                    "title" => "Summary",
                    "goal" => "",
                    "objectives" => "",
                    "description" => "Kids CodeLab",
                    "assignment_description" => "",
                    "assignment_url" => "",
                    "material_url" => "https://linkschoolonline.com/assets/materials/scratch-summary.pdf",
                    "video_url" => "https://youtu.be/UWR1JnIUAdY",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/86829896685?pwd=OxuWHkyEZ2TVXe5rwJlZ6cnLyqk4XF.1",
                    "recorded_url" => "",
                    "date" => "2025-07-12 12:00"
                ],
                [
                    "id" => 10,
                    "course_id" => 1,
                    "course_name" => "Scratch Programming",
                    "title" => "Congratulations",
                    "goal" => "Congratulations on your Participation in the Scratch Programming Course!",
                    "objectives" => "",
                    "description" => "Final Day & Certificate!",
                    "assignment_description" => "",
                    "assignment_url" => "",
                    "material_url" => "",
                    "video_url" => "https://youtu.be/UWR1JnIUAdY",
                    "reading_url" => 1,
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "",
                    "recorded_url" => "",
                    "date" => "2025-07-12 12:00"
                ],
            ],

            2 => [
                [
                    "id" => 1,
                    "course_id" => 2,
                    "course_name" => "Graphic Design",
                    "title" => "Recap",
                    "goal" => "",
                    "objectives" => "",
                    "description" => "Kids Coding Fest",
                    "assignment_description" => "",
                    "assignment_url" => "",
                    "material_url" => "https://linkschoolonline.com/assets/materials/Recap-graphic.pdf",
                    "video_url" => "https://youtu.be/I1l96BUVrv4?si=eMPcPmk7-k_U22mO",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/89830371647?pwd=vp9CpARWTVGIp5R7hffSqOes3bb8aB.1",
                    "recorded_url" => "https://drive.google.com/file/d/1MoSFgx8_RwSlPVWhaagGBRwm1Fn3zdwp/preview",
                    "date" => "2025-05-17 12:00"
                ],
                [
                    "id" => 2,
                    "course_id" => 2,
                    "course_name" => "Graphic Design",
                    "title" => "Lesson 1",
                    "goal" => "Understand how graphic design is used in the real world.",
                    "objectives" => "Help kids understand what graphic design is all about",
                    "description" => "Introduction to Storytelling using Generative AI",
                    "assignment_description" => "",
                    "assignment_url" => "https://linkschoolonline.com/assets/materials/intro-to-story-telling-project.pdf",
                    "material_url" => "https://linkschoolonline.com/assets/materials/introduction-to-story-telling-using-ai.pdf",
                    "video_url" => "https://youtu.be/I1N7IGcgRg4?si=9gjsbt-BZN3pyLkG",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/89830371647?pwd=vp9CpARWTVGIp5R7hffSqOes3bb8aB.1",
                    "recorded_url" => "https://drive.google.com/file/d/1tQGnECsHYM9SKFS-RRYaVquTC2dX_dR4/preview",
                    "date" => "2025-05-24 12:00"
                ],
                [
                    "id" => 3,
                    "course_id" => 2,
                    "course_name" => "Graphic Design",
                    "title" => "Lesson 2",
                    "goal" => "Understand how graphic design is used in the real world.",
                    "objectives" => "Help kids understand what graphic design is all about",
                    "description" => "Exploring AI Image Generators",
                    "assignment_description" => "",
                    "assignment_url" => "https://linkschoolonline.com/assets/materials/exploring-ai-image-generators-project.pdf",
                    "material_url" => "https://linkschoolonline.com/assets/materials/exploring-ai-image-generators.pdf",
                    "video_url" => "https://youtu.be/7FWl9RP7viE",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/89830371647?pwd=vp9CpARWTVGIp5R7hffSqOes3bb8aB.1",
                    "recorded_url" => "https://drive.google.com/file/d/1tLzIVTts8CeGUzv3GI89fZKJK8xBVvV0/preview",
                    "date" => "2025-05-31 12:00"
                ],
                [
                    "id" => 4,
                    "course_id" => 2,
                    "course_name" => "Graphic Design",
                    "title" => "Lesson 3",
                    "goal" => "Understand how graphic design is used in the real world.",
                    "objectives" => "Help kids understand what graphic design is all about",
                    "description" => "Designing our Storybook Cover",
                    "assignment_description" => "",
                    "assignment_url" => "https://linkschoolonline.com/assets/materials/story-cover-project.pdf",
                    "material_url" => "https://linkschoolonline.com/assets/materials/story-cover.pdf",
                    "video_url" => "https://youtu.be/qTUCg4nIb6Y",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/89830371647?pwd=vp9CpARWTVGIp5R7hffSqOes3bb8aB.1",
                    "recorded_url" => "https://drive.google.com/file/d/1LSOVYJeAhE6oeefMeRax6hAkRGl_IVbh/preview",
                    "date" => "2025-06-07 12:00"
                ],
                [
                    "id" => 5,
                    "course_id" => 2,
                    "course_name" => "Graphic Design",
                    "title" => "Lesson 4",
                    "goal" => "Understand how graphic design is used in the real world.",
                    "objectives" => "Help kids understand what graphic design is all about",
                    "description" => "Building a Story World",
                    "assignment_description" => "",
                    "assignment_url" => "https://linkschoolonline.com/assets/materials/building-a-story-world-project.pdf",
                    "material_url" => "https://linkschoolonline.com/assets/materials/building-a-story-world.pdf",
                    "video_url" => "https://youtu.be/bf9l3GnMwfU",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/89830371647?pwd=vp9CpARWTVGIp5R7hffSqOes3bb8aB.1",
                    "recorded_url" => "https://drive.google.com/file/d/1oLDsnHzvA2u6fQrNodtu8EAnXxU1SavX/preview",
                    "date" => "2025-06-14 12:00"
                ],
                [
                    "id" => 6,
                    "course_id" => 2,
                    "course_name" => "Graphic Design",
                    "title" => "Lesson 5",
                    "goal" => "Understand how graphic design is used in the real world.",
                    "objectives" => "Help kids understand what graphic design is all about",
                    "description" => "Basics of Animation",
                    "assignment_description" => "",
                    "assignment_url" => "https://linkschoolonline.com/assets/materials/basics-of-animation-project.pdf",
                    "material_url" => "https://linkschoolonline.com/assets/materials/basics-of-animation.pdf",
                    "video_url" => "https://youtu.be/3Jc7TW6LIlk",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/89830371647?pwd=vp9CpARWTVGIp5R7hffSqOes3bb8aB.1",
                    "recorded_url" => "https://drive.google.com/file/d/1_veRPeK0nQu5t2JjBzSaJjbEMNE1eirw/preview",
                    "date" => "2025-06-21 12:00"
                ],
                [
                    "id" => 7,
                    "course_id" => 2,
                    "course_name" => "Graphic Design",
                    "title" => "Lesson 6",
                    "goal" => "Understand how graphic design is used in the real world.",
                    "objectives" => "Help kids understand what graphic design is all about",
                    "description" => "Comic Strip Creation",
                    "assignment_description" => "",
                    "assignment_url" => "https://linkschoolonline.com/assets/materials/comic-strip-creation-project.pdf",
                    "material_url" => "https://linkschoolonline.com/assets/materials/comic-strip-creation.pdf",
                    "video_url" => "https://youtu.be/T86lE3CwatM",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/89830371647?pwd=vp9CpARWTVGIp5R7hffSqOes3bb8aB.1",
                    "recorded_url" => "https://drive.google.com/file/d/14uCjcFyb_mGclrL6PTlpEnOrztYYmTnr/preview",
                    "date" => "2025-06-28 12:00"
                ],
                [
                    "id" => 8,
                    "course_id" => 2,
                    "course_name" => "Graphic Design",
                    "title" => "Lesson 7",
                    "goal" => "Understand how graphic design is used in the real world.",
                    "objectives" => "Help kids understand what graphic design is all about",
                    "description" => "Voice and Sound for Storytelling",
                    "assignment_description" => "",
                    "assignment_url" => "https://linkschoolonline.com/assets/materials/sound-and-voice.pdf",
                    "material_url" => "https://linkschoolonline.com/assets/materials/sound-and-voice.pdf",
                    "video_url" => "https://youtu.be/gLc4i-AylDM",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/89830371647?pwd=vp9CpARWTVGIp5R7hffSqOes3bb8aB.1",
                    "recorded_url" => "",
                    "date" => "2025-07-05 12:00"
                ],
                [
                    "id" => 9,
                    "course_id" => 2,
                    "course_name" => "Graphic Design",
                    "title" => "Summary",
                    "goal" => "Understand how graphic design is used in the real world.",
                    "objectives" => "Help kids understand what graphic design is all about",
                    "description" => "Kids CodeLab",
                    "assignment_description" => "",
                    "assignment_url" => "",
                    "material_url" => "https://linkschoolonline.com/assets/materials/summary-graphics-code.pdf",
                    "video_url" => "https://youtu.be/4rFT320e2sM",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/89830371647?pwd=vp9CpARWTVGIp5R7hffSqOes3bb8aB.1",
                    "recorded_url" => "",
                    "date" => "2025-07-12 12:00"
                ],
                [
                    "id" => 10,
                    "course_id" => 2,
                    "course_name" => "Graphic Design",
                    "title" => "Congratulations",
                    "goal" => "Congratulations on your Participation in the Graphics Design Course!",
                    "objectives" => "",
                    "description" => "Final Day & Certificate!",
                    "assignment_description" => "",
                    "assignment_url" => "",
                    "material_url" => "",
                    "video_url" => "https://youtu.be/4rFT320e2sM",
                    "reading_url" => 1,
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "",
                    "recorded_url" => "",
                    "date" => "2025-07-12 12:00"
                ],
            ],

            3 => [
                [
                    "id" => 1,
                    "course_id" => 3,
                    "course_name" => "Web Development",
                    "title" => "Recap",
                    "goal" => "",
                    "objectives" => "",
                    "description" => "Web Development",
                    "assignment_description" => "",
                    "assignment_url" => "",
                    "material_url" => "https://linkschoolonline.com/assets/materials/Recap-web-development.pdf",
                    "video_url" => "https://youtu.be/bUe7olftF5g?si=Pe-Xky6OIlUyuQsr",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/87298339379?pwd=jXL6aTb4NNzhLuD3LhorTBQMcvapiU.1",
                    "recorded_url" => "https://us06web.zoom.us/j/85102292466?pwd=Gk3SgIlGKCpREeOk6QnlPpdjP2MgG8.1",
                    "date" => "2025-08-11 10:00"
                ],
                [
                    "id" => 2,
                    "course_id" => 3,
                    "course_name" => "Web Development",
                    "title" => "Lesson 1",
                    "goal" => "Help kids understand what a website is, why it's important, and how it works.",
                    "objectives" => "Teach kids the basics of web design, including HTML, CSS, and website building tools, to create their own functional websites.",
                    "description" => "Introduction to Websites and WordPress",
                    "assignment_description" => "",
                    "assignment_url" => "",
                    "material_url" => "https://linkschoolonline.com/assets/materials/Introduction-to-Websites-and-WordPress.pdf",
                    "video_url" => "https://youtu.be/EAeBUdVS3gU?si=nBbI1ir0sGkv-AWG",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/87298339379?pwd=jXL6aTb4NNzhLuD3LhorTBQMcvapiU.1",
                    "recorded_url" => "",
                    "date" => "2025-05-24 12:00"
                ],
                [
                    "id" => 3,
                    "course_id" => 3,
                    "course_name" => "Web Development",
                    "title" => "Lesson 2",
                    "goal" => "Help kids understand what a website is, why it's important, and how it works.",
                    "objectives" => "Teach kids the basics of web design, including HTML, CSS, and website building tools, to create their own functional websites.",
                    "description" => "Themes and Customization",
                    "assignment_description" => "",
                    "assignment_url" => "",
                    "material_url" => "https://linkschoolonline.com/assets/materials/Themes-and-Customization.pdf",
                    "video_url" => "https://youtu.be/A_5KmyAp3nM",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/87298339379?pwd=jXL6aTb4NNzhLuD3LhorTBQMcvapiU.1",
                    "recorded_url" => "https://drive.google.com/file/d/1tQyK_aMG_UCHrFfUnIeGYPelbscS26s6/preview",
                    "date" => "2025-05-31 12:00"
                ],
                [
                    "id" => 4,
                    "course_id" => 3,
                    "course_name" => "Web Development",
                    "title" => "Lesson 3",
                    "goal" => "Help kids understand what a website is, why it's important, and how it works.",
                    "objectives" => "Teach kids the basics of web design, including HTML, CSS, and website building tools, to create their own functional websites.",
                    "description" => "Content Creation (Post vs Pages)",
                    "assignment_description" => "",
                    "assignment_url" => "",
                    "material_url" => "https://linkschoolonline.com/assets/materials/content-creation.pdf",
                    "video_url" => "https://youtu.be/3kBel3--IWE",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/87298339379?pwd=jXL6aTb4NNzhLuD3LhorTBQMcvapiU.1",
                    "recorded_url" => "https://drive.google.com/file/d/1qLaE049srJxV39l3l18Dfv9Nt6M6nNnO/preview",
                    "date" => "2025-06-07 12:00"
                ],
                [
                    "id" => 5,
                    "course_id" => 3,
                    "course_name" => "Web Development",
                    "title" => "Lesson 4",
                    "goal" => "Help kids understand what a website is, why it's important, and how it works.",
                    "objectives" => "Teach kids the basics of web design, including HTML, CSS, and website building tools, to create their own functional websites.",
                    "description" => "Menus and Widgets",
                    "assignment_description" => "",
                    "assignment_url" => "https://linkschoolonline.com/assets/materials/menu-and-widgets-project.pdf",
                    "material_url" => "https://linkschoolonline.com/assets/materials/Menus-and-Widgets.pdf",
                    "video_url" => "https://youtu.be/cH8RFsggrKk",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/87298339379?pwd=jXL6aTb4NNzhLuD3LhorTBQMcvapiU.1",
                    "recorded_url" => "https://drive.google.com/file/d/14CjA8Xk8dAko6-VziKUy5KYh2CWiXKzk/preview",
                    "date" => "2025-06-14 12:00"
                ],
                [
                    "id" => 6,
                    "course_id" => 3,
                    "course_name" => "Web Development",
                    "title" => "Lesson 5",
                    "goal" => "Help kids understand what a website is, why it's important, and how it works.",
                    "objectives" => "Teach kids the basics of web design, including HTML, CSS, and website building tools, to create their own functional websites.",
                    "description" => "Embedding Media",
                    "assignment_description" => "",
                    "assignment_url" => "https://linkschoolonline.com/assets/material/embeding-media-project.png",
                    "material_url" => "https://linkschoolonline.com/assets/material/Embedding-Media.pdf",
                    "video_url" => "https://youtu.be/LBNXxAURvdk",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/87298339379?pwd=jXL6aTb4NNzhLuD3LhorTBQMcvapiU.1",
                    "recorded_url" => "https://drive.google.com/file/d/19KYM93i-y8X-GI3QC9zYDMkBw_LWJ9Uq/preview",
                    "date" => "2025-06-21 12:00"
                ],
                [
                    "id" => 7,
                    "course_id" => 3,
                    "course_name" => "Web Development",
                    "title" => "Lesson 6",
                    "goal" => "Help kids understand what a website is, why it's important, and how it works.",
                    "objectives" => "Teach kids the basics of web design, including HTML, CSS, and website building tools, to create their own functional websites.",
                    "description" => "Plugins Presentation",
                    "assignment_description" => "",
                    "assignment_url" => "",
                    "material_url" => "https://linkschoolonline.com/assets/material/Plugins-Presentation.pdf",
                    "video_url" => "https://youtu.be/ImOvbzCB8c4",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/87298339379?pwd=jXL6aTb4NNzhLuD3LhorTBQMcvapiU.1",
                    "recorded_url" => "https://drive.google.com/file/d/1aG-_GacmQOOH8ff3BCmeCPegewYmEfmJ/preview",
                    "date" => "2025-06-28 12:00"
                ],
                [
                    "id" => 8,
                    "course_id" => 3,
                    "course_name" => "Web Development",
                    "title" => "Lesson 7",
                    "goal" => "Help kids understand what a website is, why it's important, and how it works.",
                    "objectives" => "Teach kids the basics of web design, including HTML, CSS, and website building tools, to create their own functional websites.",
                    "description" => "Building a Min Project",
                    "assignment_description" => "",
                    "assignment_url" => "https://linkschoolonline.com/assets/material/wordpress-final-project.jpg",
                    "material_url" => "https://linkschoolonline.com/assets/material/Building-a-Mini-Project.pdf",
                    "video_url" => "https://youtu.be/ECrYUDIcR1g",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/87298339379?pwd=jXL6aTb4NNzhLuD3LhorTBQMcvapiU.1",
                    "recorded_url" => "",
                    "date" => "2025-07-05 12:00"
                ],
                [
                    "id" => 9,
                    "course_id" => 3,
                    "course_name" => "Web Development",
                    "title" => "Summary",
                    "goal" => "Help kids understand what a website is, why it's important, and how it works.",
                    "objectives" => "Teach kids the basics of web design, including HTML, CSS, and website building tools, to create their own functional websites.",
                    "description" => "Building a Min Project",
                    "assignment_description" => "",
                    "assignment_url" => "",
                    "material_url" => "https://linkschoolonline.com/assets/material/Building-a-Mini-Project.pdf",
                    "video_url" => "https://youtu.be/VvDibd4vZuY",
                    "reading_url" => "",
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "https://us06web.zoom.us/j/87298339379?pwd=jXL6aTb4NNzhLuD3LhorTBQMcvapiU.1",
                    "recorded_url" => "",
                    "date" => "2025-07-12 12:00"
                ],
                [
                    "id" => 10,
                    "course_id" => 3,
                    "course_name" => "Web Development",
                    "title" => "Congratulations",
                    "goal" => "Congratulations on your Participation in the Website Development Course!",
                    "objectives" => "",
                    "description" => "Final Day & Certificate!",
                    "assignment_description" => "",
                    "assignment_url" => "",
                    "material_url" => "",
                    "video_url" => "https://youtu.be/VvDibd4vZuY",
                    "reading_url" => 1,
                    "has-quiz" => 0,
                    "is_final" => 0,
                    "zoom_url" => "",
                    "recorded_url" => "",
                    "date" => "2025-07-12 12:00"
                ],
            ],
        ];
    }
}
